- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
    - name: Print a task Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com
  

- name: Demo on Inventory variables
  hosts: all
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"

- name: Demo on File variables
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"


-  name: Demo on facts
   hosts: all
   tasks:
      - name: Print facts veriable
        ansible.builtin.debug:
          msg: "hostname {{ansible_fqdn}}"

-  name: Demo on register veriable
   hosts: all
   tasks: 
     - name: Print register veriable
       ansiblebuiltin.shell: uptime
       register: out

     - name: Print output
       ansible.builtin.debug:
         msg: "out"

