- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
    - name: Print a task Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars: task.google.com
  
